name: CI

on:
  push:
  pull_request:

jobs:
  build_ps2:
    runs-on: windows-2019
    steps:
      # 1) Check out repo
      - uses: actions/checkout@v4

      # 2) Set up Python 3.11 (or whatever version you prefer)
      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      # 3) Build ARK (the same commands you run locally)
      - name: Build ARK
        run: |
          python dependencies\python\configure_build.py ps2
          dependencies\windows\ninja.exe

      # 4) Build ISO with ImgBurn
      #    Adapt the paths for your .ibb file and resulting .iso
      - name: Build ISO
        run: |
          .\dependencies\windows\imgburn.exe ^
            /MODE BUILD ^
            /BUILDMODE IMAGEFILE ^
            /FILESYSTEM "ISO9660 + UDF" ^
            /UDFREV "1.02" ^
            /VOLUMELABEL "GH2_UNIFIED" ^
            /OVERWRITE YES ^
            /ROOTFOLDER NO ^
            /NOIMAGEDETAILS ^
            /SRC ".\out\ps2\" ^
            /DEST ".\out\gh2_u.iso" ^
            /START ^
            /CLOSE

      # 5) Run ps2master on the newly created ISO
      - name: Master the ISO (ps2master.exe)
        run: |
          .\dependencies\windows\ps2master.exe .\out\gh2_u.iso

      # 6) Upload the final ISO artifact
      - name: Upload result
        uses: actions/upload-artifact@v4
        with:
          name: GH2_UNIFIED
          path: .\out\gh2_u.iso
